environments:
  - environmentType: DEMO
    url: http://kotuszkowo.pl
    title: Kotuszkowo- blog o kotach
    browser: CHROME
    isActive: false
  - environmentType: UAT
    url: https://www.filmweb.pl/
    title: Filmweb - filmy takie jak Ty!
    browser: FIREFOX
    isActive: false
  - environmentType: PROD
    url: http://logback.qos.ch/
    title: Logback Home
    browser: EDGE
    isActive: true